### ISSUE TITLE
100% zoom is not 100%

### ISSUE THREAD

**Issue by dy** [ZMYaro/paintz#111]
**Describe the bug**
With 100% zoom I see something different than 100% zoom:
![image](https://user-images.githubusercontent.com/300067/52861397-5a85f400-3100-11e9-9368-cd9cd248868a.png)
As you see, pencil line width fluctuates 1-2 px.
The brush has antialiasing artifacts:
![image](https://user-images.githubusercontent.com/300067/52861486-98831800-3100-11e9-84a7-6b6ab75237b7.png)

If I save the file, that is saved ok:
![image](https://user-images.githubusercontent.com/300067/52861462-843f1b00-3100-11e9-96f2-ff636ab58e01.png)

**Expected behavior**
Expexted to see 1:1 pixel matching, the actual 100% zoom.

**Environment**
 - Device:  Lenovo x280
 - OS: Windows 10 pro 1803
 - Browser: Brave Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)

**Comment by ZMYaro** [comment]
It looks like you might have your browser zoom set higher than 100%.

In the menu, make sure your zoom level is 100% (this screenshot is from Chrome, but I assume Brave has a similar control).
![zoom](https://user-images.githubusercontent.com/763405/52880906-3db5e480-3131-11e9-8503-f5a40c274ccd.png)

Additionally, in your browser settings, confirm page zoom is set to 100% (again, this screenshot is from Chrome, but you can search for “zoom” in your browser's settings).
![zoom_setting](https://user-images.githubusercontent.com/763405/52881060-92f1f600-3131-11e9-8ace-9c98ba17946f.png)

**Comment by dy** [comment]
![image](https://user-images.githubusercontent.com/300067/52894062-b76dc280-3171-11e9-9b9c-09347583c888.png)

**Comment by ZMYaro** [comment]
Comparing that screenshot to PaintZ running at 100% zoom, it looks like you have some amount of zoom.  Here is a screenshot with your screenshot alongside PaintZ at 100% zoom:
![image](https://user-images.githubusercontent.com/763405/52896042-599ca300-3190-11e9-82a8-365fa6133d73.png)

Have you checked whether you have some amount of zoom set at the browser level?  If that is also set at 100%, you could check at the OS level—on some computers (including mine, actually) Windows will default to a zoom level higher than 100%, and you can manually change it in Windows Settings → System → Display.

**Comment by dy** [comment]
Ah, yes, I have system fonts size at 125% - otherwise fonts are too small. Mb that’s the reason

**Comment by dy** [comment]
100% size looks fine
![image](https://user-images.githubusercontent.com/300067/52906877-de84cc80-3223-11e9-9cb6-997712d5ee30.png)
Not sure if you'd like to fix that

**Comment by ZMYaro** [comment]
I am not sure there is a way I _can_ fix it.  I can control the image data on the canvas, but I do not decide how web browsers choose to display it.

**Comment by dy** [comment]
`window.devicePixelRatio` gives value `1.25` for `125%` system zoom and `1` for `100%` system zoom.

**Comment by ZMYaro** [comment]
Yes, but how are you suggesting I handle a `devicePixelRatio` that is not `1`?  If I intentionally override the user's preferred scaling, that feels like a potential accessibility issue.

**Comment by dy** [comment]
I wonder if that script would help to separate device zoom from browser zoom
https://codepen.io/reinis/pen/RooGOE

**Comment by ZMYaro** [comment]
Again, it is not a question of how to detect the zoom, but whether that is actually a better user experience.  Right now, I am inclined to keep the current experience, in which the UI and the canvas both match the user's preferred zoom level, which is what MS Paint does.

**Comment by dy** [comment]
Not sure I understand current experience - I hardly can imagine a designer/person able to tolerate these visual artifacts.

**Comment by ZMYaro** [comment]
As I understand it, you are suggesting I override any user who selects a zoom level other than 100%.  That seems like a worse experience for users who want that higher zoom level, either because they are visually impaired, or because they are using high-density displays.

**Comment by dy** [comment]
You have in-app zoom, not sure why you consider some zoom level a worse user experience. Now default zoom level _is_ worse experience, no way to make 1:1 drawings, and all derived zooms are off now too, so that seems like you rather ignore such users. I mean my job is just to inform, you decide.

**Comment by ZMYaro** [comment]
I am sorry you find the current PaintZ experience (and the MS Paint experience it is intended to replicate) not to your liking.  Again, I believe forcibly setting the canvas zoom level to 1 canvas pixel = 1 screen pixel would provide a worse experience for users who manually set higher zoom levels because they are visually impaired, as well as users whose devices default to higher zoom levels because they have high density displays (such as the Chromebook Pixel, which defaults to 2×).

If you want, you can set the canvas zoom level to counter your system zoom—you said you have your system zoom set to 125%, so you could set your PaintZ canvas zoom to 80% (1.25 × 0.80 = 1.00) to get your desired 1:1 canvas.
