### ISSUE TITLE
Add the ability to resize selections

### ISSUE THREAD

**Issue by PickleBen806** [ZMYaro/paintz#113]
**Is your feature request related to a problem?  Please describe.**
I can't stretch or enlarge images.

**Solution**
Add a dot on every side and corner of a selection that can be selected and dragged to stretch the selection, as in MS Paint.

If shift+dragging has been added to the rectangle and oval tools, add it to this as well.

(Edited by @ZMYaro)

**Comment by ZMYaro** [comment]
Pushed back to a separate version because the best way I can think of to implement this is going to require much more work, and it is worth getting the rest of v3.2 to users and shipping this later.

**Comment by ZMYaro** [comment]
The implementation in the [resizable-selections](https://github.com/ZMYaro/paintz/tree/resizable-selections) branch is now (\*knocks on wood\*) fully functional!  Still needs more testing before merging it into master, but this is definitely going to make it into v3.3 (\*knocks on more wood\*).
