### ISSUE TITLE
Plz add layers

### ISSUE THREAD

**Issue by KillerKat11** [ZMYaro/paintz#159]
if u r an artist then you will know how important layers are.

**Comment by ZMYaro** [comment]
Of course I know the value of layers.  In more complex drawing programs, such as GIMP and Photoshop, they are invaluable.  However, tools like those already exist for the web \(my favorite at the moment being [Photopea](https://photopea.com)\).  Where Photopea aims to offer a web/CrOS alternative to Photoshop, PaintZ aims to offer a web/CrOS alternative to MS Paint.  Thus, complex features, such as layers, are generally going to be left out in favor of keeping PaintZ lightweight and fast, like classic MS Paint.

**Comment by KillerKat11** [comment]
thank you
