### ISSUE TITLE
Add the "Invert Color" feature of MSPaint for selected areas

### ISSUE THREAD

**Issue by Oldsniper** [ZMYaro/paintz#180]
MSPaint has a feature which is valuable when printing images with light-on-black backgrounds. Rather than using up liters of black ink, these images can be converted to inverse colored images which are easy to print and view. In MSPaint, this feature was called by right clicking the selected area - a drop-down menu offered:
invert selection
...
invert color
These options could be added to the pop-up toolbar in PaintZ when right clicking the selected area.

**Comment by ZMYaro** [comment]
Tentatively adding this to 3.2, but it might get pushed back.

**Comment by ZMYaro** [comment]
Moving to v4.0 because it will fit better as a toolbar option when paste gets moved out of the selection toolbox, and that will require the move to the new file system API to balance the file toolbox, which is not being added until v4.0.

**Comment by ZMYaro** [comment]
Tentatively moving to v3.3; might get pushed back depending on time.

**Comment by ZMYaro** [comment]
Accidentally forgot to add the icon to the offline cache manifest; fixed in https://github.com/ZMYaro/paintz/commit/af4c08c8220769a9ddc9e07dbe73944f9f561d6a.
