### ISSUE TITLE
Add Print icon to PaintZ for printing

### ISSUE THREAD

**Issue by areynolds2021** [ZMYaro/paintz#194]
Unless I'm missing seeing it, I don't see a print icon in PaintZ. I see a Save icon, but no Print icon. Could you add one?

**Comment by ZMYaro** [comment]
This could possibly be enabled by hiding everything but the canvas with `@media print`.

**Comment by ZMYaro** [comment]
Reopening so I remember I need to add an entry to the help dialog.

**Comment by ZMYaro** [comment]
Added to help dialog in https://github.com/ZMYaro/paintz/commit/99731353620f31dd92be5d1111ec2f2757ff42c4.
