### ISSUE TITLE
Ending a file name with a period adds an extra period before the file extension

### ISSUE THREAD

**Issue by ZMYaro** [ZMYaro/paintz#218]
**Steps to reproduce the behavior**
1. Open the Save as dialog.
2. Enter a file name ending with a period (e.g, “example.”).
3. The file extension is added with an extra period (e.g., “example..png” or “example..jpg”).

**Expected behavior**
The file name should be appended using the existing period (e.g., “example.png” or “example.jpg”).

(Caught by David Martin.)

**Comment by ZMYaro** [comment]
Also confirm this expected behavior is mentioned in the comprehensive test plan.

**Comment by Mattarouen** [comment]
#24

**Comment by ZMYaro** [comment]
@Mattarouen #24 appears to be unrelated to this issue.  Did you mean to mention a different issue?

**Comment by ZMYaro** [comment]
Fixed in https://github.com/ZMYaro/paintz/commit/a572b62456438d34b36c109da370c7b062ebbccd.
Test plan updated in https://github.com/ZMYaro/paintz/commit/1a41786bff2e524616a21973ccce717dd54cdbe7.
