### ISSUE TITLE
Undo is control+z instead of command+z on OS X

### ISSUE THREAD

**Issue by skykooler** [zmyaro/paintz#23]

**Comment by zmyaro** [comment]
Functionality should be fixed in https://github.com/zmyaro/paintz/commit/475866341e79997420672e0fca4856fdc33ce930.  The UI changes will arrive later.

**Comment by zmyaro** [comment]
UI changes implemented in https://github.com/zmyaro/paintz/commit/2f75b7e10a781fc04973efb0b204eb05d6771e53.
