### ISSUE TITLE
Selecting all sometimes fills with the fill color

### ISSUE THREAD

**Issue by ZMYaro** [ZMYaro/paintz#255]
**Describe the bug**
Sometimes, using the “Select all” function fills the canvas with the current fill color until the selection is moved.

**Steps to reproduce the behavior**
1. Open a fresh PaintZ window or open an image.
2. Select the rectangular selection tool.
3. Select an arbitrary region.
4. Select the ”Select all“ button (or Ctrl+A).

**Expected behavior**
The entire canvas should be selected.

**Actual behavior**
The entire canvas gets selected, but the selection is filled with the current fill color until the selection is transformed.

**Environment**
 - OS: Windows 10, Windows 11
 - Browser: Chrome 104 and 107
**CANNOT** reproduce on Edge 104 or Firefox 104 for Windows or on Chrome 104 or Firefox 103 for Android.

**Comment by ZMYaro** [comment]
https://user-images.githubusercontent.com/763405/186576751-b5f16db8-b7aa-4b42-ba40-96fbe278e120.mp4

**Comment by ZMYaro** [comment]
With a friend's help, I we ruled out
* Android
  - Chrome 104
  - Firefox 103
* iOS
  - Safari 15
* MacOS
  - Chrome 104
  - Firefox 103
  - Safari 15
* Windows
  - Edge 104
  - Firefox 104

I am going to assume this is a bug in Chrome for Windows and not prioritize looking into it for now unless it starts happening elsewhere, but I will leave it open for now just in case.

**Comment by lizzyd710** [comment]
I know you already tested on a bunch of platforms but just to help be thorough, tested on Red Hat Linux (RHEL 9), with Firefox 91.12.0esr and it didn't happen for me. Let me know if you want me to test any other browsers on this platform!

**Comment by ZMYaro** [comment]
@lizzyd710 Thank you for checking that!

**Comment by ZMYaro** [comment]
Note for future!me: I had PaintZ 3.2 cached in one of my test browsers on one of my Windows machines, and it still happens there (Chrome 107), so it was _not_ caused by the selection tool changes in PaintZ 3.3.
