### ISSUE TITLE
Web app not loading (specs in details)

### ISSUE THREAD

**Issue by lizzyd710** [ZMYaro/paintz#262]
**Describe the bug**
I went to the [PaintZ web app](https://www.paintz.app) to do a quick drawing but it is stuck on the loading screen. I was hesitant to report this since it could just be something only happening to me, but I figured it would be better to bring it to attention and it not being relevant than the alternative.

**Expected behavior**
To see the main PaintZ screen

**Actual behavior**
The PaintZ loading screen with the circle continuously loading

**Screenshots**
![image](https://user-images.githubusercontent.com/12602768/203155962-e9da9c16-880d-4fe1-a9c4-a2176774a042.png)

**Environment**
 - Device: HP Laptop
 - OS: Windows 10
 - Browser: Firefox 107.0

**Additional context**
When I opened up the Firefox dev tools there was the following warning: `Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-125332101-1”.` Not sure if that would be related, though.

**Comment by ZMYaro** [comment]
I am unable to reproduce this issue (currently Firefox 107 on Windows 10 and 11; also tried Chrome).  Failing to load the Google Analytics script should not prevent the rest of the app loading (I just tested with that URL manually blocked to confirm it still worked).

At the risk of suggesting the obvious, did you check for any issues with your Internet connection or try a clear cache + hard reload?

**Comment by lizzyd710** [comment]
There were no issues with loading up other websites, including websites I had never been to. I also tried in a private browsing window, so presumably there was no cache it was looking at? But regardless, I tried just now and it worked fine, so...\*shrug*

Sorry for any undue worry!
