### ISSUE TITLE
Add the ability to rotate/flip the entire image

### ISSUE THREAD

**Issue by ZMYaro** [ZMYaro/paintz#30]

**Comment by zmyaro** [comment]
https://design.google.com/icons/#ic_rotate_left
https://design.google.com/icons/#ic_rotate_right
https://design.google.com/icons/#ic_flip

**Comment by ZMYaro** [comment]
Flipping implemented in https://github.com/ZMYaro/paintz/commit/b3e1016c4bbbbe1dfa2e75cb3573db4a26daccbc.

**Comment by ZMYaro** [comment]
Rotating implemented in https://github.com/ZMYaro/paintz/commit/55d140b2025c8240fcce1a3d8f2a42330f1b5685.
