### ISSUE TITLE
Add the option to disable anti-aliasing

### ISSUE THREAD

**Issue by andrumar10** [zmyaro/paintz#37]
Pretty self explanatory. Would be nice to be able to turn this on or off for crisper lines.

**Comment by zmyaro** [comment]
Could you explain what you mean?  Are you talking about the anti-aliasing?

**Comment by andrumar10** [comment]
Yup! I was trying to do some pixel art on the new version to be used for some monochrome OLED displays and found myself not able to use any of the shape tools because of the anti-aliasing.

**Comment by zmyaro** [comment]
I agree, there should be a way to turn that off.  I will tentatively mark this for v2.4.

**Comment by zmyaro** [comment]
Pushing this back since canvas currently has no support for turning off anti-aliasing.

**Comment by zmyaro** [comment]
Putting this back in 2.4 because I want 2.4 to have more features, and there is at least one workaround that might be promising.

**Comment by zmyaro** [comment]
Added in https://github.com/zmyaro/paintz/pull/57.  Finally!
