### ISSUE TITLE
Add H & W next to pixel entry fields in Resize window

### ISSUE THREAD

**Issue by andrumar10** [zmyaro/paintz#38]
It'd be nice to have H & W or "Height" and "Width" next to the respective entry fields in the resize window, Also perhaps edit the description of the Resize option in the Help popup to indicate both cropping and resize actions can be taken.

**Comment by zmyaro** [comment]
The fields do show “Width” and “Height” when they are blank.  I might add text labels in the future, but for now, I am treating that as [wontfix] for the foreseeable future.

I like your other suggestion, though, and I updated both the help description and the icon's mouseover text in https://github.com/zmyaro/paintz/commit/1212fc463b32d7d41f7e6fa38bbb52e23450d35d.
