### ISSUE TITLE
[FEATURE] add file handlers in manifest to be able to open file from CrOS FileBrowser

### ISSUE THREAD

**Issue by grandrew** [ZMYaro/paintz#5]
Add file handlers as described in
https://developer.chrome.com/apps/manifest/file_handlers for supported file types

and support for `app.runtime.onLaunched` event to pick filename

**Comment by zmyaro** [comment]
Is there any way to add this support without making a packaged app wrapper around PaintZ?

**Comment by grandrew** [comment]
AFAIK there is only a background.js event listener requirement to implement this. And packaged apps seem to be deprecated

**Comment by zmyaro** [comment]
This feature is being put off because, for the moment, only a packaged app can register a file handler in its manifest.

**Comment by ZMYaro** [comment]
More is happening with this in Chrome now - https://bugs.chromium.org/p/chromium/issues/detail?id=829689

**Comment by ZMYaro** [comment]
This is not going to happen via the Chrome App route, however support for the upcoming file handling API has been added for v3.3 (see #198)!
