### ISSUE TITLE
Curve tool glitching out while is on pencil tool?

### ISSUE THREAD

**Issue by BorkiLork** [ZMYaro/paintz#68]
Ive been trying to work on something till the curve tool started glitching out. Can someone help?

**Comment by zmyaro** [comment]
Could you describe in more detail what you did just before the curve tool started glitching out?

**Comment by ZMYaro** [comment]
@BorkiLork: The curve tool was overhauled in PaintZ 3.  Did that fix the issue for you?

**Comment by ZMYaro** [comment]
@BorkiLork: The curve tool was overhauled in PaintZ 3.  Did that fix the issue for you?

**Comment by ZMYaro** [comment]
@BorkiLork I wanted to check in again to ask whether you are still having that issue with the curve tool.  Otherwise I will assume the changes in PaintZ 3.0 fixed it and close this issue.
