### ISSUE TITLE
Add donation link to “About” dialog

### ISSUE THREAD

**Issue by ZMYaro** [ZMYaro/paintz#77]

**Comment by zmyaro** [comment]
Possible icons:
https://material.io/icons/#ic_attach_money
https://material.io/icons/#ic_monetization_on

**Comment by zmyaro** [comment]
Have a “?” icon that displays a clarification message onmouseover (e.g., “PaintZ is free and always will be, but small donations help keep development going and really are appreciated.”).

**Comment by ZMYaro** [comment]
Added in https://github.com/ZMYaro/paintz/commit/dd908b3a5f0dccd85538bbd8d18f53df6c327e1f.

Left “?” icon out for now since “Buy me a coffee” does not imply any sort of software features gained through donations, and the coffee icon (https://material.io/icons/#ic_local_cafe) is less blunt than the money icons.
