### ISSUE TITLE
PaintZ fails to initialize if unable to access localStorage

### ISSUE THREAD

**Issue by ZMYaro** [ZMYaro/paintz#78]
Some browsers (most notably Mobile Safari) throw errors when attempting to use `localStoarage` functions in private tabs.  PaintZ should still be usable in private tabs, and just accept that settings will be deleted after the current session.

**Comment by zmyaro** [comment]
Not loading settings from `localStorage` on every setting check will also allow people to have multiple PaintZ instances with different settings.

**Comment by ZMYaro** [comment]
Fixed in https://github.com/ZMYaro/paintz/commit/1ae94e279ecb9f48a78ba09e452266973d47a1b9.
