### ISSUE TITLE
Add layers so several images can be worked without damaging the others

### ISSUE THREAD

**Issue by pescamillam** [ZMYaro/paintz#89]

**Comment by ZMYaro** [comment]
@pescamillam: Is this an MS Paint feature?  It sounds like you are describing the layers feature from programs like Photoshop, GIMP, and the like, which are beyond the scope of this project.

**Comment by pescamillam** [comment]
@ZMYaro is your scope MS Paint features? I think layers like GIMP would be really useful for people who want to use this to mix several images, personally I hate how when drawing an image over another the one behind gets damaged, it was just a suggestion

**Comment by ZMYaro** [comment]
PaintZ is intended to be an MS Paint substitute.  If you are looking for a web-based Photoshop/GIMP/Paint.NET substitute, I recommend [Photopea](https://www.photopea.com), or you could also try [Pixlr Editor](https://pixlr.com/editor/) (though it requires Flash Player).
