### ISSUE TITLE
Add translucent brush options

### ISSUE THREAD

**Issue by pescamillam** [ZMYaro/paintz#92]

**Comment by ZMYaro** [comment]
As far as I am aware, MS Paint does not have alpha for colors, so I am inclined to call this out of the scope of the project.

**Comment by ParodyVerse** [comment]
Actually, there is a tool for that. It's called marker mode for the curve tool.

**Comment by ZMYaro** [comment]
@ParodyVerse: Are you talking about the alternate brushes in Win7 Paint, or something else?

**Comment by ParodyVerse** [comment]
in the toolbar, to the left of the colors, there are two drop-down menus, one for the outline, and one for the fill. there are a number of fill-types, including marker. the marker is what I'm talking about.

**Comment by ZMYaro** [comment]
Ah, OK.  I hadn't prioritized those because I was prioritizing classic MS Paint features over Win7 Paint ones, but I will keep this ticket open for if/when I have time to work on those.

**Comment by ParodyVerse** [comment]
Okay.

**Comment by ZMYaro** [comment]
I just realized while going through old tickets there has actually been one open for this for a while 🤦.

**Comment by ZMYaro** [comment]
Duplicate of https://github.com/ZMYaro/paintz/issues/42.
