### ISSUE TITLE
Text wrapping for text without spaces is not saved

### ISSUE THREAD

**Issue by pescamillam** [ZMYaro/paintz#93]
When I write a text box the result is different from what I'm seeing just before exiting the text box:
![image](https://user-images.githubusercontent.com/362688/43752521-00a02440-99c7-11e8-9013-677bffbc7406.png)
![image](https://user-images.githubusercontent.com/362688/43752528-0af30534-99c7-11e8-8158-88013e2a837e.png)

**Comment by ZMYaro** [comment]
Fixed in https://github.com/ZMYaro/paintz/commit/c47cd7a4528056094adaa77ec5aea4bf2f9fb94e.
